name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/setup

      - name: Run lint
        run: npm run lint
